name: pa
recipe: symfony

config:
  php: '7.4'
  webroot: public
  xdebug: false
  via: nginx:1.18
  database: postgres:12
  cache: redis:5

services:
  appserver_nginx:
    scanner: false
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  node:
    type: node:14
  database:
    portforward: 50432

tooling:
  redis-cli:
    service: cache
  yarn:
    service: node

proxy:
  mailhog:
    - mailhog-pa.lndo.site
