#admin:
    #resource: ../../src/Controller/Admin
    #type: annotation
    #prefix: /admin
    #name_prefix: admin_

front:
    resource: ../../src/Controller/
    type: annotation
    name_prefix: front_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
