admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin
    name_prefix: admin_

front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: front_

api:
    resource: ../../src/Controller/API
    type: annotation
    prefix: /api
    name_prefix: api_
security:
    resource: ../../src/Controller/Security
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
